### ISSUE TITLE
Links to toc/doc in index files KO due to absolute URI

### ISSUE THREAD

**Issue by arkamy** [cmarchand/xsl-doc#1]
In the index file, the links to toc & doc file use absolute URI. It's not portable.

I succeed to use relative URI with the following code in makeIndex.xsl
`<frame name="toc" src="{string-join(($intermediaryDirectory,tokenize(@tocOutputUri,'/')[last()]),'/')}"/>`
`<frame name="doc" src="{string-join(($intermediaryDirectory,tokenize(@htmlOutputUri,'/')[last()]),'/')}"/>`

**Comment by cmarchand** [comment]
Patch applied in 6ed8e39b197b42d62a174da07fc043b157d62ba1

**Comment by cmarchand** [comment]
I have missed a commit somewhere...

**Comment by cmarchand** [comment]
solved in commit aba70ff
